### ISSUE TITLE
Documentation missing on ReadTheDocs 

### ISSUE THREAD

**Issue by MrBeardedGuy** [mherrmann/helium#117]
Just noticed the Helium docs are [not showing up](https://selenium-python-helium.readthedocs.io/en/latest/api.html) on readthedocs.io anymore.

**Comment by mherrmann** [comment]
It's now at https://helium.readthedocs.io/en/latest/ but https://helium.readthedocs.io/en/latest/api.html is broken until somebody fixes it. See #115.
