### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by kamikaze** [mherrmann/helium#7]
Can we get geckodriver for arm64v8?

**Comment by mherrmann** [comment]
Did you read https://github.com/mherrmann/helium/blob/master/README.md#status-of-this-project ?

**Comment by kamikaze** [comment]
no, i figured out that you are still using selenium crap. no need, yet another dead project based on that. good luck

**Comment by mherrmann** [comment]
Haha, okay kid. Good luck in the real world.

**Comment by qqgg231** [comment]
Probably fixed by https://github.com/mherrmann/selenium-python-helium/commit/6b970dcf170968ffccb3c833d391b71fa14b8447

Helium will now use drivers on PATH if available

**Comment by qqgg231** [comment]
duplicate of #1, fixed
